name: CI

on:
  repository_dispatch:
    types: trigger-workflow
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo apt-get install python3-pip
          sudo apt-get install xvfb xserver-xephyr vnc4server
          sudo pip3 install pyvirtualdisplay
          pip3 install -r requirements.txt
          python3 auto_joiner.py
        env:
          TEAMS_ID: ${{ secrets.TEAMS_ID }}
          TEAMS_PASS: ${{ secrets.TEAMS_PASS }}
